services:
  account:
    image: elshandunyamaliyev/account:v1
    container_name: account_container
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms_bank
  card:
    image: elshandunyamaliyev/card:v1
    container_name: card_container
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms_bank
  loan:
    image: elshandunyamaliyev/loan:v1
    container_name: loan_container
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms_bank

networks:
  ms_bank:
    driver: "bridge"