apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-ms-deployment
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: elshandunyamaliyev/account:v4
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: msbank-configmap
                  key: ACCOUNTS_APPLICATION_NAME
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://accountsdb:5432/postgres
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: msbank-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: msbank-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: msbank-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: msbank-configmap
                  key: RABBITMQ_HOST

            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: msbank-configmap
                  key: RABBITMQ_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080