apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loansdb
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: loansdb
spec:
  selector:
    app: loansdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
